language: node_js

node_js:
  - "12.16"    

dist: trusty
sudo: required

cache:
  directories:
    - ./node_modules

install:
  - npm install

branches:
  only:
  - develop

before_script:
  - npm install -g @angular/cli

script:
- ng build